### ISSUE TITLE
Can't instantiate abstract class AzureSynapseConnectionManager with abstract methods get_response

### ISSUE THREAD

**Issue by neednlab** [embold-health/dbt-azuresynapse#15]
Hello, 

I'm trying to develop Azure Synapse Analytics - Dedicated SQL pool with dbt.
There is an error occurred when I executed "dbt run".

env: Windows 10, Python 3.7.5, dbt version 0.19.1

![image](https://user-images.githubusercontent.com/41602171/117527849-82bfdd00-b001-11eb-956c-7019da708adf.png)

**Comment by dataders** [comment]
Can you share the output when you type `dbt --version`?

My guess is that your version of dbt is greater than what is supported by `dbt-azuresynapse`. I suggest you try `dbt-synapse`.

**Comment by neednlab** [comment]
@swanderz Thanks for your reply
 my local dev environment is shown as followings

> installed version: 0.19.1
   latest version: 0.19.1

> Plugins:
    - bigquery: 0.19.1     
    - postgres: 0.19.1     
    - redshift: 0.19.1     
    - snowflake: 0.19.1    
    - spark: 0.19.1        
    - sqlserver: 0.19.0.2  
    - synapse: 0.19.0.1 

In addition, I tried DB connection type: sqlserver in my profile file as well,  that is used "dbt-synapse" module, right?
There is another runtime SQL error when creating CCI. I think it is due to Synapse SQL pool created table as  CLUSTERED COLUMNSTORE INDEX by default.
`CREATE CLUSTERED COLUMNSTORE INDEX stg_my_first_dbt_model__dbt_tmp_cci
    ON stg.my_first_dbt_model__dbt_tmp`

**Comment by dataders** [comment]
Ah sorry looks like some docs need to be updated. You should have `type=synapse` in your profile that changed in v0.18.0. Also you're using the dbt-synapse adapter, not the dbt-azuresynapse adapter where we're discussing now

**Comment by neednlab** [comment]
@swanderz 
It works after I changed the type to `synapse` and removed `authentication` configuration item in my profile file.
thx!
